#! /bin/sh
sxhkd &

bspc config border_width        1
bspc config window_gap         10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#c5c8c6'
bspc config presel_feedback_color '#b5bd68'
bspc config click_to_focus true
bspc config honor_size_hints true

bspc rule -a Gimp follow=on
bspc rule -a Flashplayer state=pseudo_tiled

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false

mpd &
setsid compton --config ~/.config/compton.conf &
nitrogen --restore &
nm-applet &

~/scripts/auto_monitor.sh &
