#! /bin/sh

# prevent annoying sxhkd spam when already running
if [ $(pgrep -cx sxhkd) -gt 1 ] ; then
	echo "sxhkd is running."
else
	sxhkd &
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        1
bspc config window_gap         10

bspc config split_ratio         0.50
#bspc config borderless_monocle  true
#bspc config gapless_monocle     true
bspc config single_monocle      true

bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#c5c8c6'
bspc config presel_feedback_color '#b5bd68'
bspc config click_to_focus button1
#bspc config honor_size_hints true

bspc rule -a Gimp follow=on
bspc rule -a Flashplayer state=pseudo_tiled

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
#bspc config merge_overlapping_monitors false
bspc config merge_overlapping_monitors true

#mpd &

xrdb -I$HOME ~/.Xresources
compton &
xsetroot -cursor_name left_ptr &
~/.fehbg &
polybar example &
nm-applet --indicator &
